---
title: "DSlecture17"
author: "Hening CUi"
date: "11/10/2021"
output: github_document
---

```{r,echo = FALSE}
library (tidyverse)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = 0.6,
  out.width = "90%"
)

options(
  ggplot2.continuous.color = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_color_discrete = scale_color_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

## lists
youcan put anything

```{r}

l =list(
vec_numeric = 5:8,
vec_logical = c(TRUE, TRUE, FALSE, FALSE, FALSE, TRUE),
mat = matrix(1:8, nrow = 2),
summary = summary(rnorm(100)))
```

```{r}
l
l$vec_numeric
l[[1]]
mean(l[["vec_numeric"]])
```


## for loop

```{r}
list_norm =
  list(
    a = rnorm(20, mean = 3, sd = 1),
    b = rnorm(30, mean = 0, sd = 5),
    c = rnorm(40, mean = 10, sd = .2),
    d = rnorm(20, mean = -3, sd = 1)
  )
```


```{r}
list_norm
```

pause and get my function

```{r}
mean_and_sd = function(x){
  if (!is.numeric(x)){
    stop("input must be numeric")
  }
  
  if (length(x) < 3){
    stop("input must have at least 3 number")
  }
  
 mean_x = mean(x)
 sd_x = sd(x)
 tibble::tibble(
   mean = mean_x,
   sd = sd_x
 )
}
```

i can apply to each element

```{r}
mean_and_sd(list_norm[[1]])
mean_and_sd(list_norm[[2]])
mean_and_sd(list_norm[[3]])
mean_and_sd(list_norm[[4]])
```

let use for loop


```{r}
output = vector("list", length = 4)

for(i in 1:4){
  output[[i]] = mean_and_sd(list_norm[[i]])}
```

## let try map

```{r}
output = map(list_norm, mean_and_sd)
```
what if different function

```{r}
output = map(list_norm, IQR)
```

```{r}
output = map_dbl(list_norm, IQR)
```

```{r}
output = map_df(list_norm, mean_and_sd, .id = "input")
```

## list column

```{r}
listcol_df = 
  tibble(
    name = c("a", "b", "c", "d"), 
    samp = list_norm
  )

```

```{r}
listcol_df %>% 
  pull(name)
listcol_df %>% pull(samp)
listcol_df %>% filter(name == "a")
```

lets try some operation
```{r}
mean_and_sd(listcol_df$samp[[1]])

```

can i just map

```{r}
map(listcol_df$samp, mean_and_sd)
```
can i list a column

```{r}
listcol_df %>% 
  mutate(summary = map_df(samp, mean_and_sd),
         medians = map_dbl(samp, median))
```







